-- You can use this file to load seed data into the database using SQL statements
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('62','SHELL ALEXANDRA','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('50','SHELL ANG MO KIO AVE 6','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('3','SHELL BOON LAY','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('35','SHELL BRADDELL','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('78','SHELL BUKIT BATOK NP','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('26','SHELL BUKIT BATOK RD','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('65','SHELL BUKIT PANJANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('63','SHELL BUKIT TIMAH HILL','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('18','SHELL CHANGI KEMBANGAN','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('28','SHELL CHOA CHU KANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('49','SHELL COMMONWEALTH/STIRLING RD','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('70','SHELL DUNEARN ENG NEO','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('67','SHELL DUNEARN UNIVERSITY','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('9','SHELL DUNMAN','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('12','SHELL EAST COAST','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('4','SHELL GEYLANG LOR 7','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('10','SHELL GUILLEMARD','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('55','SHELL HAVELOCK','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('68','SHELL JALAN AHMAD IBRAHIM','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('58','SHELL JURONG WEST','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('40','SHELL LAKE VIEW ','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('81','SHELL MACPHERSON','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('64','SHELL MARSILING','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('31','SHELL MOULMEIN','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('59','SHELL NEWTON CIRCUS ','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('82','SHELL NEWTON HOOPER RD','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('57','SHELL OUTRAM 305','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('74','SHELL PASIR PANJANG 168','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('75','SHELL PASIR PANJANG 328','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('22','SHELL PASIR RIS','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('17','SHELL PAYA LEBAR MACPHERSON','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('16','SHELL PAYA LEBAR PIE','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('33','SHELL PIERCE RESERVOIR','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('83','SHELL PUNGGOL','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('54','SHELL QUEENSWAY ANCHORAGE','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('27','SHELL SELETAR HILLS','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('30','SHELL SEMBAWANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('48','SHELL SENGKANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('36','SHELL SERANGOON GARDEN','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('44','SHELL SERANGOON ROAD','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('2','SHELL SIGLAP','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('19','SHELL SIMPANG BEDOK','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('38','SHELL SIN MING','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('14','SHELL TAMPINES AVE 2','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('20','SHELL TAMPINES AVE 4','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('80','SHELL TANJONG KATONG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('53','SHELL TELOK BLANGAH','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('43','SHELL THOMSON NOVENA','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('61','SHELL TIONG BAHRU','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('42','SHELL TOA PAYOH','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('76','SHELL UPPER BUKIT TIMAH PIE','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('13','SHELL UPPER CHANGI','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('25','SHELL UPPER SERANGOON HOUGANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('39','SHELL UPPER THOMSON MANDAI','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('51','SHELL WOODLANDS AVE 9','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('73','SHELL WOODLANDS MANDAI','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('29','SHELL YIO CHU KANG','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('1','SHELL YISHUN AVE 5','System','System',NOW(),NOW(),'active');
INSERT INTO stations (id, name, creator, updater, created_at, updated_at, status) VALUES ('24','SHELL YISHUN RING','System','System',NOW(),NOW(),'active');
